### ISSUE TITLE
Merging preview and main window into single window

### ISSUE THREAD

**Issue by TheMisir** [Dropsource/monarch#17]
First of all thanks for building such an amazing tool!

I would be happy if the both windows (preview, story tree) could be  merged into one window so it would be a bit easy to work with stories while coding on side. May I know the reason why you've decided to put them on separate windows?

**Comment by fertrig** [comment]
Thank you, @TheMisir!

We put them on separate windows because it is a simple implementation that guarantees the visual isolation of your stories. By rendering a story on its on window, we can make sure that full screen interactions (e.g. modals, navigation and some animations) render as you would expect.

However, we recognize that having multiple windows is not an ideal experience. We are thinking of doing a "dock" feature which would let you keep the windows together. We are also exploring another experience which may be even better.

Stay tuned. This is something we want to improve sooner rather than later.

**Comment by fertrig** [comment]
Dock feature added with [release 1.3.0](https://monarchapp.io/blog/version_1.3.0)
