### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by DevNico** [Dropsource/monarch#8]
Monarch seems to be entirely written in dart so why not use the dart package ecosystem. Instead of the long and cumbersome tutorial on https://monarchapp.io/docs/install. Why not publish a monarch package that can be installed with `pub global activate monarch`?

**Comment by fertrig** [comment]
Monarch is a combination of applications: a CLI executable, a native desktop app, and a Flutter app. There is also the monarch flutter package. The native desktop apps are written in Swift for macOS, C++ for Windows, and probably will be written in C++ for Linux. pub.dev is not meant to distribute desktop app executables.

In the future we will look at simpler options like Homebrew, Chocolatey or the App Stores of each platform. We couldn't do Homebrew because Homebrew doesn't distribute brand-new projects. Also, flutter desktop was so new that the App Stores were not an option.

Stay tuned though, making the install easier is in our roadmap.

**Comment by DevNico** [comment]
Alright thanks for the info. Awesome work so far keep it up!
